## Aufgabe 1

In [67]:
import numpy as np

score = np.array([103, 1502, 6230, 3, 1682, 5241, 4532])
print(score) # print unsorted array

score_sorted = np.sort(score) # sort array
print(score_sorted) # print sorted array

indices = np.array([np.where(score == x)[0][0] for x in score_sorted]) # get indices of sorted elements
print(indices)

[ 103 1502 6230    3 1682 5241 4532]
[   3  103 1502 1682 4532 5241 6230]
[3 0 1 4 6 5 2]
